# SITE CONFIGURATION
title: Coral Conservation Genomics and Ecology  # your site title
author: Zac H. Forsman, Phd # You :P
description: > # Meta description of Homepage
  Coral reef ecosystems are rapidly collapsing.
  What can DNA teach us about the past present and future of coral reefs?
  Can ecology and genetics guide reef restoration?
baseurl:  "" # the subpath of your site, e.g. /blog
url: "https://zacforsman.github.io/" # the base hostname & protocol for your site, e.g. http://example.com

# SEO PLUGIN
social:
  name: zacforsman
  links:
    - https://twitter.com/ZacForsman
    - https://www.facebook.com/ZacForsman
    - https://www.linkedin.com/in/ZacForsman
    - https://github.com/zacforsman

# THEME SETTINGS
navigation: # Navigation links
  - {name: 'Home', link: '/'}
  - {name: 'HIMB Coral Nursery', link: '/himb-coral-nursery'}
  - {name: 'Publications', link: '/publications'}
  - {name: 'About', link: '/about'}


tagline: >
  Zac H. Forsman, PhD

hero_img: /images/reef-exposed.jpg # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/sleek_lg.jpg

email: zac@hawaii.edu # email for form submission

twitter_username: ZacForsman # replace with your_twitter_username or comment to remove link from footer
github_username:  zacforsman # replace with your_github_username or comment to remove link from footer
instagram_username: ZacForsman # replace with your_instagram_username or comment to remove link from footer

disqus:
  shortname:  # to enable comments replace with your_disqus_shortname

# google_tag_manager: GTM-XXXXXXX # Uncomment to enable GTM. Replace GTM-XXXXXXX with your GTM container ID

service_worker: true

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null
# theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
